name: Deploy to Fly.io

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Fly app name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build image
        run: docker build -t urlshort-mvp:deploy .
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --app ${{ github.event.inputs.app_name }} --remote-only --build-arg BUILDKIT_INLINE_CACHE=1
